coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        target: 0%
        threshold: 0%
        base: auto
        informational: true

    patch:
      default:
        target: 0%
        base: auto
        only_pulls: true
        informational: true

comment:
  layout: "header,diff,flags,components,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

  # Show changes in PR comments
  branches: null

github_checks:
  annotations: true

ignore:
  - "tests/"
  - "**/*_test.rs"
  - "**/main.rs"

flags:
  unittests:
    paths:
      - src/
    carryforward: false
